/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package banorte;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ModProyecto extends javax.swing.JFrame {
    int IDproyecto, horasHombre,numIniciativa, tamRegistro=3217, idGer=0, opcion, term=0;
        String nombreP="",direcGral="",liderpro="", objetivo="", indicadores="", pruebaid="";
        String fecha="", status="", consultor="", cualitativas="", cuantitativas="";
        String kpiSeg="", id="";
        int idpr=0;
        boolean terminado=false;
    /**
     * Creates new form ModProyecto
     */
    public ModProyecto() {
        this.setTitle("Modificar proyecto");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        textArea1 = new java.awt.TextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduzca su ID. (8 dígitos)");

        jButton1.setText("Introducir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Diga el ID del proyecto a modificar. (Véase en la caja de texto anterior)");

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Introduzca el ID del gerente que registrará proyecto. (8 dígitos)");

        jLabel4.setText("Introduzca el nombre del proyecto");

        jLabel5.setText("Introduzca la dirección General del proyecto.");

        jLabel6.setText("Introduzca el líder del proyecto.");

        jLabel7.setText("Introduzca el objetivo del proyecto.");

        jLabel8.setText("Introduzca el número de iniciativas. (En número)");

        jLabel9.setText("Introduzca Indicadores (KPI): riesgo, costo, nivel de servicio, ingreso");

        jLabel10.setText("Introduzca la fecha dd/mm/aaa.");

        jLabel11.setText("Introduzca el número de horas. (En número)");

        jLabel12.setText("Introduzca los beneficios cualitativos.");

        jLabel13.setText("Introduzca los beneficios cuantativos.");

        jLabel14.setText("Introduzca KPI (key performance Indicator)");

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setText("Proyecto terminado? 1) Si. 2) No.  (Introducir número)");

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Introduzca el estatus del proyectopreparación, diagnóstico, rediseño, piloto, implementación, seguimiento");

        jLabel17.setText("Introduzca el nombre del consultor.");

        jLabel18.setText("NOTA: Llenar todos los campos para no tener error.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textArea1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jTextField4)
                                .addComponent(jTextField5)
                                .addComponent(jTextField6)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField16)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jButton3)))
                            .addComponent(jLabel18))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        textArea1.setText("");
        try {
            RandomAccessFile miArchivito=new RandomAccessFile("Proyectos.dat","rw");
            int contador=0, pruebaId;
            int IDproyecto, horasHombre,numIniciativa, tamRegistro=3217, idGer=0, opcion, identificador=0;
            String nombreP="",direcGral="",liderpro="", objetivo="", indicadores="", pruebaid="";
            String fecha="", status="", consultor="", cualitativas="", cuantitativas="";
            String kpiSeg="", linea="";
            boolean terminado=false;
            int numRegistros=(int)(miArchivito.length()/tamRegistro);
            boolean encontrado=false;
            pruebaid="1"+jTextField1.getText();
            pruebaId=Integer.parseInt(pruebaid);
            while((contador<numRegistros)){
                miArchivito.seek(contador*tamRegistro);
                identificador=miArchivito.readInt();
                if(pruebaId==identificador){
                    miArchivito.seek(contador*tamRegistro+4);
                    terminado=miArchivito.readBoolean();
                    IDproyecto=miArchivito.readInt();
                    for(int i=0; i<100; i++)
                        nombreP+=miArchivito.readChar();
                    for(int i=0; i<100; i++)
                        direcGral+=miArchivito.readChar();
                    for(int i=0; i<50; i++)
                        liderpro+=miArchivito.readChar();
                    for(int i=0; i<200; i++)
                        objetivo+=miArchivito.readChar();
                    numIniciativa=miArchivito.readInt();
                    for(int i=0; i<30; i++)
                        indicadores+=miArchivito.readChar();
                    for(int i=0; i<10; i++)
                        fecha+=miArchivito.readChar();
                    for(int i=0; i<30; i++)
                        status+=miArchivito.readChar();
                    for(int i=0; i<50; i++)
                        consultor+=miArchivito.readChar();
                    horasHombre=miArchivito.readInt();
                    for(int i=0; i<500; i++)
                        cualitativas+=miArchivito.readChar();
                    for(int i=0; i<500; i++)
                        cuantitativas+=miArchivito.readChar();
                    for(int i=0; i<30; i++)
                        kpiSeg+=miArchivito.readChar();
                    if(terminado){
                        linea = "Proyecto del usuario: " + identificador + "\nID proyecto: " + IDproyecto + "\nNombre proyecto: " + nombreP + "\nProyecto terminado" + "\nDirección general: " + direcGral
                                + "\nLíder Proyecto: " + liderpro + "\nObjetivo del proyecto: " + objetivo + "\nNo. de iniciativa: " + numIniciativa + "\nIndicadores KPI: " + indicadores
                                + "\nFecha proyecto " + fecha + "\nEstatus del proyecto: " + status + "\nConsultor: " + consultor + "\nNúmero de horas: "
                                + horasHombre + "\nVentajas cualitativas: " + cualitativas + "\nVentajas cuantitativas: " + cuantitativas + "\nIndicadores KPI: " + kpiSeg + "\n\n";
                        textArea1.append(linea);
                    }
                    else{
                        linea = "Proyecto del usuario: " + identificador + "\nID proyecto: " + IDproyecto + "\nNombre proyecto: " + nombreP + "\nProyecto no terminado" + "\nDirección general: " + direcGral
                                + "\nLíder Proyecto: " + liderpro + "\nObjetivo del proyecto: " + objetivo + "\nNo. de iniciativa: " + numIniciativa + "\nIndicadores KPI: " + indicadores
                                + "\nFecha proyecto " + fecha + "\nEstatus del proyecto: " + status + "\nConsultor: " + consultor + "\nNúmero de horas: "
                                + horasHombre + "\nVentajas cualitativas: " + cualitativas + "\nVentajas cuantitativas: " + cuantitativas + "\nIndicadores KPI: " + kpiSeg + "\n\n";
                        textArea1.append(linea);
                    }

                    nombreP=direcGral=liderpro=objetivo=indicadores=pruebaid="";
                    fecha=status=consultor=cualitativas=cuantitativas="";
                    kpiSeg="";
                    encontrado=true;
                }
                contador++;
        }
            if(!encontrado)
                textArea1.setText("ID sin proyectos o mal introducido. \nIntente de nuevo.");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MostrarProyectos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MostrarProyectos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {                                         
            // TODO add your handling code here:
            RandomAccessFile miArchivito=new RandomAccessFile("Proyectos.dat","rw");
            RandomAccessFile miArchivoFinalizados = new RandomAccessFile("ProyectoFinalizado.dat","rw");
            int horasHombre=0, numIniciativa=0, idGer=0;
            String nombreP="",direcGral="",liderpro="", objetivo="", indicadores="";
            String fecha="", status="", consultor="", cualitativas="", cuantitativas="";
            String kpiSeg="", id="";
            int numRegistros=(int)miArchivoFinalizados.length()/tamRegistro;
            int contador=0;
            boolean t=false, existe=false;
            int term=0;
            id=jTextField3.getText();
            idGer=Integer.parseInt(id);
            nombreP=jTextField4.getText();
            if(nombreP.length()<100){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=nombreP.length(); i<100; i++)
                    nombreP+=" ";
            }
            else{
                nombreP=nombreP.substring(0,100);
            }
            direcGral=jTextField5.getText();
            if(direcGral.length()<100){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=direcGral.length(); i<100; i++)
                    direcGral+=" ";
            }
            else{
                direcGral=direcGral.substring(0,100);
            }
            liderpro=jTextField6.getText();
            if(liderpro.length()<50){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=liderpro.length(); i<50; i++)
                    liderpro+=" ";
            }
            else{
                liderpro=liderpro.substring(0,50);
            }
            
            objetivo=jTextField7.getText();
            if(objetivo.length()<200){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=objetivo.length(); i<200; i++)
                    objetivo+=" ";
            }
            else{
                objetivo=objetivo.substring(0,200);
            }
            
            String iniciativa=jTextField8.getText();
            numIniciativa=Integer.parseInt(iniciativa);
            indicadores=jTextField9.getText();
            if(indicadores.length()<30){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=indicadores.length(); i<30; i++)
                    indicadores+=" ";
            }
            else{
                indicadores=indicadores.substring(0,30);
            }
            
            fecha=jTextField10.getText();
            if(fecha.length()<10){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=fecha.length(); i<10; i++)
                    fecha+=" ";
            }
            else{
                fecha=fecha.substring(0,10);
            }
            
            status=jTextField17.getText();
            if(status.length()<30){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=status.length(); i<30; i++)
                    status+=" ";
            }
            else{
                status=status.substring(0,30);
            }
            
            consultor=jTextField11.getText();
            if(consultor.length()<50){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=consultor.length(); i<50; i++)
                    consultor+=" ";
            }
            else{
                consultor=consultor.substring(0,50);
            }
            
            String horas=jTextField12.getText();
            horasHombre=Integer.parseInt(horas);
            cualitativas=jTextField13.getText();
            if(cualitativas.length()<500){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=cualitativas.length(); i<500; i++)
                    cualitativas+=" ";
            }
            else{
                cualitativas=cualitativas.substring(0,500);
            }
            
            cuantitativas=jTextField14.getText();
            if(cuantitativas.length()<500){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=cuantitativas.length(); i<500; i++)
                    cuantitativas+=" ";
            }
            else{
                cuantitativas=cuantitativas.substring(0,500);
            }
            
            kpiSeg=jTextField15.getText();
            if(kpiSeg.length()<30){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=kpiSeg.length(); i<30; i++)
                    kpiSeg+=" ";
            }
            else{
                kpiSeg=kpiSeg.substring(0,30);
            }
            
            idpr=Integer.parseInt(jTextField2.getText());
            if(jTextField16.getText().trim().equals("")){
                term=2;
            }
            else
            {
                term=1;
            }
            if(term==1){
                t=true;
                int reg=0;
                while(contador<numRegistros){
                    miArchivoFinalizados.seek(contador*tamRegistro+5);
                    int idpro=miArchivoFinalizados.readInt();
                    if(idpro==idpr){
                        existe=true;
                        reg=contador;
                    }
                    contador++;
                }
                if (miArchivoFinalizados.length() != 0) {
                    miArchivoFinalizados.seek(miArchivoFinalizados.length());
                }
                if (!existe) {
                    miArchivoFinalizados.writeInt(idGer);
                    miArchivoFinalizados.writeBoolean(t);
                    miArchivoFinalizados.writeInt(idpr);
                    miArchivoFinalizados.writeChars(nombreP);
                    miArchivoFinalizados.writeChars(direcGral);
                    miArchivoFinalizados.writeChars(liderpro);
                    miArchivoFinalizados.writeChars(objetivo);
                    miArchivoFinalizados.writeInt(numIniciativa);
                    miArchivoFinalizados.writeChars(indicadores);
                    miArchivoFinalizados.writeChars(fecha);
                    miArchivoFinalizados.writeChars(status);
                    miArchivoFinalizados.writeChars(consultor);
                    miArchivoFinalizados.writeInt(horasHombre);
                    miArchivoFinalizados.writeChars(cualitativas);
                    miArchivoFinalizados.writeChars(cuantitativas);
                    miArchivoFinalizados.writeChars(kpiSeg);
                }
                else{
                    miArchivoFinalizados.seek(reg*tamRegistro);
                    miArchivoFinalizados.writeInt(idGer);
                    miArchivoFinalizados.writeBoolean(t);
                    miArchivoFinalizados.writeInt(idpr);
                    miArchivoFinalizados.writeChars(nombreP);
                    miArchivoFinalizados.writeChars(direcGral);
                    miArchivoFinalizados.writeChars(liderpro);
                    miArchivoFinalizados.writeChars(objetivo);
                    miArchivoFinalizados.writeInt(numIniciativa);
                    miArchivoFinalizados.writeChars(indicadores);
                    miArchivoFinalizados.writeChars(fecha);
                    miArchivoFinalizados.writeChars(status);
                    miArchivoFinalizados.writeChars(consultor);
                    miArchivoFinalizados.writeInt(horasHombre);
                    miArchivoFinalizados.writeChars(cualitativas);
                    miArchivoFinalizados.writeChars(cuantitativas);
                    miArchivoFinalizados.writeChars(kpiSeg);
                }
            }
            miArchivito.seek((idpr-1)*tamRegistro);
            miArchivito.writeInt(idGer);
            miArchivito.writeBoolean(t);
            miArchivito.writeInt(idpr);
            miArchivito.writeChars(nombreP);
            miArchivito.writeChars(direcGral);
            miArchivito.writeChars(liderpro);
            miArchivito.writeChars(objetivo);
            miArchivito.writeInt(numIniciativa);
            miArchivito.writeChars(indicadores);
            miArchivito.writeChars(fecha);
            miArchivito.writeChars(status);
            miArchivito.writeChars(consultor);
            miArchivito.writeInt(horasHombre);
            miArchivito.writeChars(cualitativas);
            miArchivito.writeChars(cuantitativas);
            miArchivito.writeChars(kpiSeg);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModProyecto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ModProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        ProyectoMod m=new ProyectoMod();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int IDproyecto, horasHombre,numIniciativa, tamRegistro=3217, idGer=0, opcion, term=0;
        String nombreP="",direcGral="",liderpro="", objetivo="", indicadores="", pruebaid="";
        String fecha="", status="", consultor="", cualitativas="", cuantitativas="";
        String kpiSeg="";
        boolean terminado=false;
        try {
            RandomAccessFile miArchivito=new RandomAccessFile("Proyectos.dat","rw");
            RandomAccessFile miArchivoFinalizados = new RandomAccessFile("ProyectoFinalizado.dat","rw");
            int numRegistros=(int)miArchivito.length()/tamRegistro;
            id=jTextField2.getText();
            int idp=Integer.parseInt(id);
            idpr=idp;
            if (idp <= numRegistros) {
                miArchivito.seek((idp - 1) * tamRegistro);
                idGer = miArchivito.readInt();
                id = Integer.toString(idGer);
                terminado = miArchivito.readBoolean();
                IDproyecto = miArchivito.readInt();
                for (int i = 0; i < 100; i++) {
                    nombreP += miArchivito.readChar();
                }
                for (int i = 0; i < 100; i++) {
                    direcGral += miArchivito.readChar();
                }
                for (int i = 0; i < 50; i++) {
                    liderpro += miArchivito.readChar();
                }
                for (int i = 0; i < 200; i++) {
                    objetivo += miArchivito.readChar();
                }
                numIniciativa = miArchivito.readInt();
                for (int i = 0; i < 30; i++) {
                    indicadores += miArchivito.readChar();
                }
                for (int i = 0; i < 10; i++) {
                    fecha += miArchivito.readChar();
                }
                for (int i = 0; i < 30; i++) {
                    status += miArchivito.readChar();
                }
                for (int i = 0; i < 50; i++) {
                    consultor += miArchivito.readChar();
                }
                horasHombre = miArchivito.readInt();
                for (int i = 0; i < 500; i++) {
                    cualitativas += miArchivito.readChar();
                }
                for (int i = 0; i < 500; i++) {
                    cuantitativas += miArchivito.readChar();
                }
                for (int i = 0; i < 30; i++) {
                    kpiSeg += miArchivito.readChar();
                }
                jTextField3.setText(id.trim());
                jTextField4.setText(nombreP.trim());
                jTextField5.setText(direcGral.trim());
                jTextField6.setText(liderpro.trim());
                jTextField7.setText(objetivo.trim());
                jTextField8.setText(Integer.toString(numIniciativa).trim());
                jTextField9.setText(indicadores.trim());
                jTextField10.setText(fecha.trim());
                jTextField17.setText(status.trim());
                jTextField11.setText(consultor.trim());
                jTextField12.setText(Integer.toString(horasHombre).trim());
                jTextField13.setText(cualitativas.trim());
                jTextField14.setText(cuantitativas.trim());
                jTextField15.setText(kpiSeg.trim());
                jTextField16.setText("");
            }
            else{
                textArea1.setText("ID no corresponde a ningun proyecto.\nIntente de nuevo.");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField17.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
                jTextField14.setText("");
                jTextField15.setText("");
                jTextField16.setText("");
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModProyecto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ModProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
