/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package banorte;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

public class RegistrarProyecto extends javax.swing.JFrame {
    private Object ex;

    /**
     * Creates new form RegistrarProyecto
     */
    public RegistrarProyecto() {
        this.setTitle("Registro de nuevo proyecto.");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduzca el ID del gerente que registrará proyecto. (8 dígitos)");

        jLabel2.setText("Introduzca el nombre del proyecto");

        jLabel3.setText("Introduzca la dirección General del proyecto.");

        jLabel4.setText("Introduzca el líder del proyecto.");

        jLabel5.setText("Introduzca el objetivo del proyecto.");

        jLabel6.setText("Introduzca el número de iniciativas. (En número)");

        jLabel7.setText("Introduzca Indicadores (KPI): riesgo, costo, nivel de servicio, ingreso");

        jLabel8.setText("Introduzca la fecha dd/mm/aaa.");

        jLabel9.setText("Introduzca el estatus del proyectopreparación, diagnóstico, rediseño, piloto, implementación, seguimiento");

        jLabel10.setText("Introduzca el nombre del consultor.");

        jLabel11.setText("Introduzca el número de horas. (En número)");

        jLabel12.setText("Introduzca los beneficios cualitativos.");

        jLabel13.setText("Introduzca los beneficios cuantativos.");

        jLabel14.setText("Introduzca KPI (key performance Indicator)");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Proyecto terminado? 1) Si. 2) No.  (Introducir número)");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3)
                        .addComponent(jTextField4)
                        .addComponent(jTextField5)
                        .addComponent(jTextField6))
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel8))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel12)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField15)
                                .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int horasHombre=0, numIniciativa=0, idGer=0;
        String nombreP="",direcGral="",liderpro="", objetivo="", indicadores="";
        String fecha="", status="", consultor="", cualitativas="", cuantitativas="";
        String kpiSeg="", id="";
        int term=0;
        id="1"+jTextField1.getText();
        idGer=Integer.parseInt(id);

        if(jTextField2.getText().trim().equals("")){
            for(int i=nombreP.length(); i<100; i++)
                    nombreP+=" ";
        }
        else{
            nombreP=jTextField2.getText();
            if(nombreP.length()<100){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=nombreP.length(); i<100; i++)
                    nombreP+=" ";
            }
            else{
               nombreP=nombreP.substring(0,100);
            }
        }
            
        if(jTextField3.getText().trim().equals("")){
            for(int i=direcGral.length(); i<100; i++)
                direcGral+=" ";
        }
        else{
            direcGral=jTextField3.getText();
            if(direcGral.length()<100){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
            for(int i=direcGral.length(); i<100; i++)
                direcGral+=" ";
            }
            else{
               direcGral=direcGral.substring(0,100);
            }
        }
        
        if(jTextField4.getText().trim().equals("")){
            for(int i=liderpro.length(); i<50; i++)
                liderpro+=" ";
        }
        else{
            liderpro=jTextField4.getText();
            if(liderpro.length()<50){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
            for(int i=liderpro.length(); i<50; i++)
                liderpro+=" ";
            }
            else{
               liderpro=liderpro.substring(0,50);
            }
        }
        
        if(jTextField5.getText().trim().equals("")){
            for(int i=objetivo.length(); i<200; i++)
                    objetivo+=" ";
        }
        else{
            objetivo=jTextField5.getText();
            if(objetivo.length()<200){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=objetivo.length(); i<200; i++)
                    objetivo+=" ";
            }
            else{
               objetivo=objetivo.substring(0,200);
            } 
        }
        
        if(jTextField6.getText().trim().equals(""))
            numIniciativa=0;
        else{                
            String iniciativa=jTextField6.getText();
            numIniciativa=Integer.parseInt(iniciativa);
        }
        
        if(jTextField7.getText().trim().equals("")){
            for(int i=indicadores.length(); i<30; i++)
                indicadores+=" ";}
        else{
            indicadores=jTextField7.getText();
            if(indicadores.length()<30){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
            for(int i=indicadores.length(); i<30; i++)
                indicadores+=" ";
            }
            else{
               indicadores=indicadores.substring(0,30);
            }
        }
         
        if(jTextField8.getText().trim().equals("")){
            for(int i=fecha.length(); i<10; i++)
                fecha+=" ";
        }
        else{
            fecha=jTextField8.getText();
            if(fecha.length()<10){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
            for(int i=fecha.length(); i<10; i++)
                fecha+=" ";
            }
            else{
               fecha=fecha.substring(0,10);
            }
        }
       
        if(jTextField9.getText().trim().equals("")){
            for(int i=status.length(); i<30; i++)
                status+=" ";
        }
        else{
            status=jTextField9.getText();
            if(status.length()<30){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
            for(int i=status.length(); i<30; i++)
                status+=" ";
            }
            else{
               status=status.substring(0,30);
            }
        }
             
        if(jTextField10.getText().trim().equals("")){
            for(int i=consultor.length(); i<50; i++)
                    consultor+=" ";
        }
        else{
            consultor=jTextField10.getText();
            if(consultor.length()<50){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=consultor.length(); i<50; i++)
                    consultor+=" ";
            }
            else{
               consultor=consultor.substring(0,50);
            }
        }
            
        
        if(jTextField11.getText().trim().equals(""))
            horasHombre=0;
        else{
            String horas=jTextField11.getText();
            horasHombre=Integer.parseInt(horas);
        }
        
        if(jTextField12.getText().trim().equals("")){
            for(int i=cualitativas.length(); i<500; i++)
                cualitativas+=" ";
        }
        else{
            cualitativas=jTextField12.getText();
            if(cualitativas.length()<500){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=cualitativas.length(); i<500; i++)
                    cualitativas+=" ";
            }
            else{
               cualitativas=cualitativas.substring(0,500);
            }
        }
                 
        if(jTextField13.getText().trim().equals("")){
            for(int i=cuantitativas.length(); i<500; i++)
                cuantitativas+=" ";
        }
        else{
            cuantitativas=jTextField13.getText();
            if(cuantitativas.length()<500){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
            for(int i=cuantitativas.length(); i<500; i++)
                cuantitativas+=" ";
            }
            else{
               cuantitativas=cuantitativas.substring(0,500);
            }
        }
        
            
        
        if(jTextField14.getText().trim().equals("")){
            for(int i=kpiSeg.length(); i<30; i++)
                kpiSeg+=" ";  
        }
        else{
           kpiSeg=jTextField14.getText();
           if(kpiSeg.length()<30){////En caso de que el dato ingresado sea menor se llena la variable de espacios.
                for(int i=kpiSeg.length(); i<30; i++)
                    kpiSeg+=" ";
            }
            else{
               kpiSeg=kpiSeg.substring(0,30);
            } 
        }
        
        if(jTextField15.getText().trim().equals(""))
            term=2;
        else{
            String terminado=jTextField15.getText();
            term=Integer.parseInt(terminado);
        }   
        try {
            int r=regProyecto(term, idGer, nombreP, direcGral, liderpro, objetivo, numIniciativa, indicadores, fecha, status, consultor, horasHombre, cualitativas, cuantitativas, kpiSeg);
            if(r==0)
                this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(RegistrarProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }

      //  this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
        public static int regProyecto(Integer term, Integer idGer, String nombreP, String direcGral, String liderpro, String objetivo, Integer numIniciativa, String indicadores, String fecha, String status, String consultor, Integer horasHombre, String cualitativas, String cuantitativas, String kpiSeg) throws IOException{ 
        // Aqui se crea un nuevo Proyecto.
        RandomAccessFile miArchivito = new RandomAccessFile("Proyectos.dat","rw");
        RandomAccessFile miArchivoFinalizados = new RandomAccessFile("ProyectoFinalizado.dat","rw");
        int tamRegistro=3217, IDproyecto;
        boolean terminado=false;
        if(term==1)
            terminado=true;
            try{
                String x=Integer.toString(idGer);
                if(x.length()==9){
                    IDproyecto = (int) ((miArchivito.length() / tamRegistro) + 1);
                    if (miArchivito.length() != 0) //Si el tamano es diferente a cero se posiciona al final del ultimo registro para poder escribir nuevos datos.
                    {
                        miArchivito.seek(miArchivito.length());
                    }
                    if (terminado) {
                        if (miArchivoFinalizados.length() != 0) {
                            miArchivoFinalizados.seek(miArchivoFinalizados.length());
                        }
                        miArchivoFinalizados.writeInt(idGer);
                        miArchivoFinalizados.writeBoolean(terminado);
                        miArchivoFinalizados.writeInt(IDproyecto);
                        miArchivoFinalizados.writeChars(nombreP);
                        miArchivoFinalizados.writeChars(direcGral);
                        miArchivoFinalizados.writeChars(liderpro);
                        miArchivoFinalizados.writeChars(objetivo);
                        miArchivoFinalizados.writeInt(numIniciativa);
                        miArchivoFinalizados.writeChars(indicadores);
                        miArchivoFinalizados.writeChars(fecha);
                        miArchivoFinalizados.writeChars(status);
                        miArchivoFinalizados.writeChars(consultor);
                        miArchivoFinalizados.writeInt(horasHombre);
                        miArchivoFinalizados.writeChars(cualitativas);
                        miArchivoFinalizados.writeChars(cuantitativas);
                        miArchivoFinalizados.writeChars(kpiSeg);
                    }
                    miArchivito.writeInt(idGer);
                    miArchivito.writeBoolean(terminado);
                    miArchivito.writeInt(IDproyecto);
                    miArchivito.writeChars(nombreP);
                    miArchivito.writeChars(direcGral);
                    miArchivito.writeChars(liderpro);
                    miArchivito.writeChars(objetivo);
                    miArchivito.writeInt(numIniciativa);
                    miArchivito.writeChars(indicadores);
                    miArchivito.writeChars(fecha);
                    miArchivito.writeChars(status);
                    miArchivito.writeChars(consultor);
                    miArchivito.writeInt(horasHombre);
                    miArchivito.writeChars(cualitativas);
                    miArchivito.writeChars(cuantitativas);
                    miArchivito.writeChars(kpiSeg);
                    ProyectoRegistrado y=new ProyectoRegistrado();
                    y.setLocationRelativeTo(null);
                    y.setVisible(true);
                    return 0;
                }
                else{
                    ErrorProy m=new ErrorProy();
                    m.setLocationRelativeTo(null);
                    m.setVisible(true);
                    return 1;
                }
                
            }catch(IOException | NumberFormatException e){
                //stdOut.println("Archivo no encontrado");
            }
        return 1;    
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
